export const ADD_TO_CART = 'add_to_cart'
export const HIDE_ORDER = 'hide_order'
export const DISPLAY_ORDER = 'display_order'
export const SET_REVIEWS = 'set_reviews'
export const SETUP_DATA = 'setup_data'
export const GET_TOTAL_BILL = 'get_total_bill'
export const PAYMENT_SUCCESS = 'payment_success'